package com.unicornlabs.kabouter.historian.data_objects;
// Generated 03/07/2012 7:11:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.List;

/**
 * Device generated by hbm2java
 */
public class Device  implements Serializable {


     private String id;
     private String ipaddress;
     private String type;
     private Integer numio;
     private List<String> ionames;
     private String displayname;
     private List<String> iotypes;
     private List<String> iodirections;

    public Device() {
    }

	
    public Device(String id, String ipaddress) {
        this.id = id;
        this.ipaddress = ipaddress;
    }
    public Device(String id, String ipaddress, String type, Integer numio, List<String> ionames, String displayname, List<String> iotypes, List<String> iodirections) {
       this.id = id;
       this.ipaddress = ipaddress;
       this.type = type;
       this.numio = numio;
       this.ionames = ionames;
       this.displayname = displayname;
       this.iotypes = iotypes;
       this.iodirections = iodirections;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getNumio() {
        return this.numio;
    }
    
    public void setNumio(Integer numio) {
        this.numio = numio;
    }
    public List<String> getIonames() {
        return this.ionames;
    }
    
    public void setIonames(List<String> ionames) {
        this.ionames = ionames;
    }
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }
    public List<String> getIotypes() {
        return this.iotypes;
    }
    
    public void setIotypes(List<String> iotypes) {
        this.iotypes = iotypes;
    }
    public List<String> getIodirections() {
        return this.iodirections;
    }
    
    public void setIodirections(List<String> iodirections) {
        this.iodirections = iodirections;
    }

}


