package com.unicornlabs.kabouter.historian.data_objects;
// Generated 03/07/2012 7:11:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PowerlogId generated by hbm2java
 */
public class PowerlogId  implements java.io.Serializable {


     private Date logtime;
     private String deviceid;

    public PowerlogId() {
    }

    public PowerlogId(Date logtime, String deviceid) {
       this.logtime = logtime;
       this.deviceid = deviceid;
    }
   
    public Date getLogtime() {
        return this.logtime;
    }
    
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }
    public String getDeviceid() {
        return this.deviceid;
    }
    
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PowerlogId) ) return false;
		 PowerlogId castOther = ( PowerlogId ) other; 
         
		 return ( (this.getLogtime()==castOther.getLogtime()) || ( this.getLogtime()!=null && castOther.getLogtime()!=null && this.getLogtime().equals(castOther.getLogtime()) ) )
 && ( (this.getDeviceid()==castOther.getDeviceid()) || ( this.getDeviceid()!=null && castOther.getDeviceid()!=null && this.getDeviceid().equals(castOther.getDeviceid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogtime() == null ? 0 : this.getLogtime().hashCode() );
         result = 37 * result + ( getDeviceid() == null ? 0 : this.getDeviceid().hashCode() );
         return result;
   }   


}


