package com.unicornlabs.kabouter.historian.data_objects;
// Generated 25/06/2012 2:06:16 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;

/**
 * PowerlogId generated by hbm2java
 */
@Embeddable
public class PowerlogId implements java.io.Serializable {

    private Date logtime;
    private String deviceid;

    public PowerlogId() {
    }

    public PowerlogId(Date logtime, String deviceid) {
        this.logtime = logtime;
        this.deviceid = deviceid;
    }

    @Column(name = "logtime", nullable = false, length = 29)
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getLogtime() {
        return this.logtime;
    }

    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    @Column(name = "deviceid", nullable = false)
    public String getDeviceid() {
        return this.deviceid;
    }

    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PowerlogId)) {
            return false;
        }
        PowerlogId castOther = (PowerlogId) other;

        return ((this.getLogtime() == castOther.getLogtime()) || (this.getLogtime() != null && castOther.getLogtime() != null && this.getLogtime().equals(castOther.getLogtime())))
                && ((this.getDeviceid() == castOther.getDeviceid()) || (this.getDeviceid() != null && castOther.getDeviceid() != null && this.getDeviceid().equals(castOther.getDeviceid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getLogtime() == null ? 0 : this.getLogtime().hashCode());
        result = 37 * result + (getDeviceid() == null ? 0 : this.getDeviceid().hashCode());
        return result;
    }
}
