package com.unicornlabs.kabouter.historian.data_objects;
// Generated 25/06/2012 2:06:16 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Powerlog generated by hbm2java
 */
@Entity
@Table(name="powerlog"
    ,schema="kabouterserver"
)
public class Powerlog  implements java.io.Serializable {


     private PowerlogId id;
     private Double power;

    public Powerlog() {
    }

	
    public Powerlog(PowerlogId id) {
        this.id = id;
    }
    public Powerlog(PowerlogId id, Double power) {
       this.id = id;
       this.power = power;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="logtime", column=@Column(name="logtime", nullable=false, length=29) ), 
        @AttributeOverride(name="deviceid", column=@Column(name="deviceid", nullable=false) ) } )
    public PowerlogId getId() {
        return this.id;
    }
    
    public void setId(PowerlogId id) {
        this.id = id;
    }
    
    @Column(name="power", precision=17, scale=17)
    public Double getPower() {
        return this.power;
    }
    
    public void setPower(Double power) {
        this.power = power;
    }




}


